# -*- coding: utf-8 -*-

mirrors = [
    'https://g2.wen.lu/',
    'https://g.alexyang.me/',
    'https://www.google.com.hk/',
    'https://fuckgfw.ggss.cf/',
    'https://www.xichuan.pub/',
    'https://g.bilibiu.cn/',
    'http://g.liyuans.win/',
    'https://gug.arukascloud.io/',
    'http://google1.5duo.ga/',
    'https://so.brosub.tk/',
    'https://g.brosub.cf/',
    'https://h.gufen.gq/',
    'https://e.aiguso.tk/',
    'https://d.freedo.gq/',
    'https://naughty-mccarthy-7033.arukascloud.io/',
    'https://nostalgic-kilby-6901.arukascloud.io/',
    'https://angry-fermi-7633.arukascloud.io/',
    'https://g.pank.one/',
    'http://g.suconghou.cn/',
    'http://google.thatsit.cc/',
    'https://kuaiguge.info/',
    'https://so.moyoo.net/',
]
